"""Consolidate all migrations and add Announcement models

Revision ID: 0001
Revises:
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=False),
    sa.Column('dob_sum_hash', sa.String(length=64), nullable=True),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('has_assigned_students', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('system_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcement_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'admin_id', name='uq_announcement_dismissal_announcement_admin')
    )
    op.create_table('banking_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('savings_apy', sa.Float(), nullable=True),
    sa.Column('savings_monthly_rate', sa.Float(), nullable=True),
    sa.Column('interest_calculation_type', sa.String(length=20), nullable=True),
    sa.Column('compound_frequency', sa.String(length=20), nullable=True),
    sa.Column('interest_schedule_type', sa.String(length=20), nullable=True),
    sa.Column('interest_schedule_cycle_days', sa.Integer(), nullable=True),
    sa.Column('interest_payout_start_date', sa.DateTime(), nullable=True),
    sa.Column('overdraft_protection_enabled', sa.Boolean(), nullable=True),
    sa.Column('overdraft_fee_enabled', sa.Boolean(), nullable=True),
    sa.Column('overdraft_fee_type', sa.String(length=20), nullable=True),
    sa.Column('overdraft_fee_flat_amount', sa.Float(), nullable=True),
    sa.Column('overdraft_fee_progressive_1', sa.Float(), nullable=True),
    sa.Column('overdraft_fee_progressive_2', sa.Float(), nullable=True),
    sa.Column('overdraft_fee_progressive_3', sa.Float(), nullable=True),
    sa.Column('overdraft_fee_progressive_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banking_settings_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('PERIOD', 'ACCOUNT', name='deletionrequesttype'), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='deletionrequeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['system_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_requests_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_requests_status'), ['status'], unique=False)

    op.create_table('feature_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('payroll_enabled', sa.Boolean(), nullable=False),
    sa.Column('insurance_enabled', sa.Boolean(), nullable=False),
    sa.Column('banking_enabled', sa.Boolean(), nullable=False),
    sa.Column('rent_enabled', sa.Boolean(), nullable=False),
    sa.Column('hall_pass_enabled', sa.Boolean(), nullable=False),
    sa.Column('store_enabled', sa.Boolean(), nullable=False),
    sa.Column('bug_reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('bug_rewards_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'block', name='uq_feature_settings_teacher_block')
    )
    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_settings_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('hall_pass_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('queue_enabled', sa.Boolean(), nullable=False),
    sa.Column('queue_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_pass_settings_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_code', sa.String(length=16), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('charge_frequency', sa.String(length=20), nullable=True),
    sa.Column('autopay', sa.Boolean(), nullable=True),
    sa.Column('waiting_period_days', sa.Integer(), nullable=True),
    sa.Column('max_claims_count', sa.Integer(), nullable=True),
    sa.Column('max_claims_period', sa.String(length=20), nullable=True),
    sa.Column('max_claim_amount', sa.Float(), nullable=True),
    sa.Column('max_payout_per_period', sa.Float(), nullable=True),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('is_monetary', sa.Boolean(), nullable=True),
    sa.Column('no_repurchase_after_cancel', sa.Boolean(), nullable=True),
    sa.Column('enable_repurchase_cooldown', sa.Boolean(), nullable=True),
    sa.Column('repurchase_wait_days', sa.Integer(), nullable=True),
    sa.Column('auto_cancel_nonpay_days', sa.Integer(), nullable=True),
    sa.Column('claim_time_limit_days', sa.Integer(), nullable=True),
    sa.Column('bundle_with_policy_ids', sa.Text(), nullable=True),
    sa.Column('bundle_discount_percent', sa.Float(), nullable=True),
    sa.Column('bundle_discount_amount', sa.Float(), nullable=True),
    sa.Column('marketing_badge', sa.String(length=50), nullable=True),
    sa.Column('tier_category_id', sa.Integer(), nullable=True),
    sa.Column('tier_name', sa.String(length=100), nullable=True),
    sa.Column('tier_color', sa.String(length=20), nullable=True),
    sa.Column('tier_level', sa.String(length=20), nullable=True),
    sa.Column('settings_mode', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_policies_policy_code'), ['policy_code'], unique=True)

    op.create_table('payroll_fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('pay_rate', sa.Float(), nullable=False),
    sa.Column('payroll_frequency_days', sa.Integer(), nullable=False),
    sa.Column('next_payroll_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('overtime_multiplier', sa.Float(), nullable=True),
    sa.Column('bonus_rate', sa.Float(), nullable=True),
    sa.Column('settings_mode', sa.String(length=20), nullable=False),
    sa.Column('daily_limit_hours', sa.Float(), nullable=True),
    sa.Column('time_unit', sa.String(length=20), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_threshold', sa.Float(), nullable=True),
    sa.Column('overtime_threshold_unit', sa.String(length=20), nullable=True),
    sa.Column('overtime_threshold_period', sa.String(length=20), nullable=True),
    sa.Column('max_time_per_day', sa.Float(), nullable=True),
    sa.Column('max_time_per_day_unit', sa.String(length=20), nullable=True),
    sa.Column('pay_schedule_type', sa.String(length=20), nullable=False),
    sa.Column('pay_schedule_custom_value', sa.Integer(), nullable=True),
    sa.Column('pay_schedule_custom_unit', sa.String(length=20), nullable=True),
    sa.Column('first_pay_date', sa.DateTime(), nullable=True),
    sa.Column('rounding_mode', sa.String(length=20), nullable=False),
    sa.Column('expected_weekly_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_settings_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('recovery_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('dob_sum_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'expired', 'cancelled', name='recovery_request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('partial_codes', sa.JSON(), nullable=True),
    sa.Column('resume_pin_hash', sa.String(length=64), nullable=True),
    sa.Column('resume_new_username', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_requests_admin_id'), ['admin_id'], unique=False)

    op.create_table('rent_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('rent_amount', sa.Float(), nullable=True),
    sa.Column('frequency_type', sa.String(length=20), nullable=True),
    sa.Column('custom_frequency_value', sa.Integer(), nullable=True),
    sa.Column('custom_frequency_unit', sa.String(length=20), nullable=True),
    sa.Column('first_rent_due_date', sa.DateTime(), nullable=True),
    sa.Column('due_day_of_month', sa.Integer(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('late_penalty_amount', sa.Float(), nullable=True),
    sa.Column('late_penalty_type', sa.String(length=20), nullable=True),
    sa.Column('late_penalty_frequency_days', sa.Integer(), nullable=True),
    sa.Column('bill_preview_enabled', sa.Boolean(), nullable=True),
    sa.Column('bill_preview_days', sa.Integer(), nullable=True),
    sa.Column('allow_incremental_payment', sa.Boolean(), nullable=True),
    sa.Column('prevent_purchase_when_late', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_settings_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('limit_per_student', sa.Integer(), nullable=True),
    sa.Column('auto_delist_date', sa.DateTime(), nullable=True),
    sa.Column('auto_expiry_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_long_term_goal', sa.Boolean(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('bundle_quantity', sa.Integer(), nullable=True),
    sa.Column('bulk_discount_enabled', sa.Boolean(), nullable=False),
    sa.Column('bulk_discount_quantity', sa.Integer(), nullable=True),
    sa.Column('bulk_discount_percentage', sa.Float(), nullable=True),
    sa.Column('collective_goal_type', sa.String(length=20), nullable=True),
    sa.Column('collective_goal_target', sa.Integer(), nullable=True),
    sa.Column('redemption_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_initial', sa.String(length=1), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('first_half_hash', sa.String(length=64), nullable=True),
    sa.Column('second_half_hash', sa.String(length=64), nullable=True),
    sa.Column('username_hash', sa.String(length=64), nullable=True),
    sa.Column('username_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('last_name_hash_by_part', sa.JSON(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('passphrase_hash', sa.Text(), nullable=True),
    sa.Column('hall_passes', sa.Integer(), nullable=True),
    sa.Column('is_rent_enabled', sa.Boolean(), nullable=True),
    sa.Column('insurance_plan', sa.String(), nullable=True),
    sa.Column('insurance_last_paid', sa.DateTime(), nullable=True),
    sa.Column('second_factor_type', sa.String(), nullable=True),
    sa.Column('second_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('has_completed_setup', sa.Boolean(), nullable=True),
    sa.Column('dob_sum', sa.Integer(), nullable=True),
    sa.Column('has_completed_profile_migration', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_half_hash'),
    sa.UniqueConstraint('second_half_hash'),
    sa.UniqueConstraint('username_hash'),
    sa.UniqueConstraint('username_lookup_hash')
    )
    op.create_table('teacher_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('steps_completed', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('demo_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('config_checking_balance', sa.Float(), nullable=True),
    sa.Column('config_savings_balance', sa.Float(), nullable=True),
    sa.Column('config_hall_passes', sa.Integer(), nullable=True),
    sa.Column('config_insurance_plan', sa.String(length=50), nullable=True),
    sa.Column('config_is_rent_enabled', sa.Boolean(), nullable=True),
    sa.Column('config_period', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('hall_pass_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pass_number', sa.String(length=3), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('decision_time', sa.DateTime(), nullable=True),
    sa.Column('left_time', sa.DateTime(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_number')
    )
    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_pass_logs_join_code'), ['join_code'], unique=False)

    op.create_table('insurance_policy_blocks',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id', 'block')
    )
    with op.batch_alter_table('insurance_policy_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_policy_blocks_block'), ['block'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_policy_blocks_policy'), ['policy_id'], unique=False)

    op.create_table('rent_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('was_late', sa.Boolean(), nullable=True),
    sa.Column('late_fee_charged', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_payments_join_code'), ['join_code'], unique=False)

    op.create_table('rent_waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('waiver_start_date', sa.DateTime(), nullable=False),
    sa.Column('waiver_end_date', sa.DateTime(), nullable=False),
    sa.Column('periods_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_item_blocks',
    sa.Column('store_item_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['store_item_id'], ['store_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_item_id', 'block')
    )
    with op.batch_alter_table('store_item_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_item_blocks_block'), ['block'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_item_blocks_item'), ['store_item_id'], unique=False)

    op.create_table('student_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('tap_enabled', sa.Boolean(), nullable=False),
    sa.Column('done_for_day_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'period', name='uq_student_blocks_student_period')
    )
    with op.batch_alter_table('student_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_blocks_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_blocks_student_id'), ['student_id'], unique=False)

    op.create_table('student_insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_payment_due', sa.DateTime(), nullable=True),
    sa.Column('coverage_start_date', sa.DateTime(), nullable=True),
    sa.Column('payment_current', sa.Boolean(), nullable=True),
    sa.Column('days_unpaid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_insurance_join_code'), ['join_code'], unique=False)

    op.create_table('student_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('store_item_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('redemption_details', sa.Text(), nullable=True),
    sa.Column('redemption_date', sa.DateTime(), nullable=True),
    sa.Column('is_from_bundle', sa.Boolean(), nullable=False),
    sa.Column('bundle_remaining', sa.Integer(), nullable=True),
    sa.Column('quantity_purchased', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_item_id'], ['store_items.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_items_join_code'), ['join_code'], unique=False)

    op.create_table('student_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_request_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_request_id'], ['recovery_requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_recovery_codes_recovery_request_id'), ['recovery_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_recovery_codes_student_id'), ['student_id'], unique=False)

    op.create_table('student_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'admin_id', name='uq_student_teachers_student_admin')
    )
    with op.batch_alter_table('student_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_teachers_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_teachers_student_id'), ['student_id'], unique=False)

    op.create_table('tap_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tap_events_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_tap_events_join_code'), ['join_code'], unique=False)

    op.create_table('teacher_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.Column('class_label', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.LargeBinary(), nullable=False),
    sa.Column('last_initial', sa.String(length=1), nullable=False),
    sa.Column('last_name_hash_by_part', sa.JSON(), nullable=False),
    sa.Column('dob_sum', sa.Integer(), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('first_half_hash', sa.String(length=64), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_blocks_claimed'), ['is_claimed'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_blocks_join_code'), ['join_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_blocks_teacher_block'), ['teacher_id', 'block'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('join_code', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date_funds_available', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_join_code'), ['join_code'], unique=False)

    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_code', sa.String(length=64), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_sysadmin_id', sa.Integer(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('reward_sent_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_sysadmin_id'], ['system_admins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reports_anonymous_code'), ['anonymous_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reports_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_insurance_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('filed_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=True),
    sa.Column('claim_item', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['student_insurance_id'], ['student_insurance.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_insurance_claims_transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_claims')
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reports_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_user_reports_anonymous_code'))

    op.drop_table('user_reports')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_join_code'))

    op.drop_table('transaction')
    with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_blocks_teacher_block'))
        batch_op.drop_index(batch_op.f('ix_teacher_blocks_join_code'))
        batch_op.drop_index(batch_op.f('ix_teacher_blocks_claimed'))

    op.drop_table('teacher_blocks')
    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tap_events_join_code'))
        batch_op.drop_index(batch_op.f('ix_tap_events_is_deleted'))

    op.drop_table('tap_events')
    with op.batch_alter_table('student_teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_teachers_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_teachers_admin_id'))

    op.drop_table('student_teachers')
    with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_recovery_codes_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_recovery_codes_recovery_request_id'))

    op.drop_table('student_recovery_codes')
    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_items_join_code'))

    op.drop_table('student_items')
    with op.batch_alter_table('student_insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_insurance_join_code'))

    op.drop_table('student_insurance')
    with op.batch_alter_table('student_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_blocks_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_blocks_period'))

    op.drop_table('student_blocks')
    with op.batch_alter_table('store_item_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_item_blocks_item'))
        batch_op.drop_index(batch_op.f('ix_store_item_blocks_block'))

    op.drop_table('store_item_blocks')
    op.drop_table('rent_waivers')
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_payments_join_code'))

    op.drop_table('rent_payments')
    with op.batch_alter_table('insurance_policy_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policy_blocks_policy'))
        batch_op.drop_index(batch_op.f('ix_insurance_policy_blocks_block'))

    op.drop_table('insurance_policy_blocks')
    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_pass_logs_join_code'))

    op.drop_table('hall_pass_logs')
    op.drop_table('demo_students')
    op.drop_table('teacher_onboarding')
    op.drop_table('students')
    op.drop_table('store_items')
    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_settings_teacher_id'))

    op.drop_table('rent_settings')
    with op.batch_alter_table('recovery_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_requests_admin_id'))

    op.drop_table('recovery_requests')
    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_settings_teacher_id'))

    op.drop_table('payroll_settings')
    op.drop_table('payroll_rewards')
    op.drop_table('payroll_fines')
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policies_policy_code'))

    op.drop_table('insurance_policies')
    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_pass_settings_teacher_id'))

    op.drop_table('hall_pass_settings')
    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_settings_teacher_id'))

    op.drop_table('feature_settings')
    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_requests_status'))
        batch_op.drop_index(batch_op.f('ix_deletion_requests_admin_id'))

    op.drop_table('deletion_requests')
    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banking_settings_teacher_id'))

    op.drop_table('banking_settings')
    op.drop_table('announcement_dismissals')
    op.drop_table('system_admins')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_timestamp'))

    op.drop_table('error_logs')
    op.drop_table('announcements')
    op.drop_table('admins')
    # ### end Alembic commands ###
