"""Clean initial migration reflecting current schema

<<<<<<<< HEAD:migrations/versions/02f217d8b08e_clean_initial_migration_reflecting_.py
Revision ID: 02f217d8b08e
Revises: 
Create Date: 2025-07-03 12:41:36.797504
========
Revision ID: a4eeffcdd4c4
Revises: 
Create Date: 2025-07-03 11:44:07.186069
>>>>>>>> main:migrations/versions/a4eeffcdd4c4_clean_initial_migration_reflecting_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/02f217d8b08e_clean_initial_migration_reflecting_.py
revision = '02f217d8b08e'
========
revision = 'a4eeffcdd4c4'
>>>>>>>> main:migrations/versions/a4eeffcdd4c4_clean_initial_migration_reflecting_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/02f217d8b08e_clean_initial_migration_reflecting_.py
    op.create_table('admin_invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=False),
========
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
>>>>>>>> main:migrations/versions/a4eeffcdd4c4_clean_initial_migration_reflecting_.py
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_initial', sa.String(length=1), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('first_half_hash', sa.String(length=64), nullable=True),
    sa.Column('second_half_hash', sa.String(length=64), nullable=True),
    sa.Column('username_hash', sa.String(length=64), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('passphrase_hash', sa.Text(), nullable=True),
    sa.Column('passes_left', sa.Integer(), nullable=True),
    sa.Column('last_tap_in', sa.DateTime(), nullable=True),
    sa.Column('last_tap_out', sa.DateTime(), nullable=True),
    sa.Column('is_rent_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_property_tax_enabled', sa.Boolean(), nullable=True),
    sa.Column('owns_seat', sa.Boolean(), nullable=True),
    sa.Column('insurance_plan', sa.String(), nullable=True),
    sa.Column('insurance_last_paid', sa.DateTime(), nullable=True),
    sa.Column('second_factor_type', sa.String(), nullable=True),
    sa.Column('second_factor_secret', sa.String(), nullable=True),
    sa.Column('second_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('has_completed_setup', sa.Boolean(), nullable=True),
    sa.Column('dob_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_half_hash'),
    sa.UniqueConstraint('second_half_hash'),
    sa.UniqueConstraint('username_hash')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tap_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('tap_in_time', sa.DateTime(), nullable=True),
    sa.Column('tap_out_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date_funds_available', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('tap_sessions')
    op.drop_table('purchase')
    op.drop_table('students')
    op.drop_table('admins')
<<<<<<<< HEAD:migrations/versions/02f217d8b08e_clean_initial_migration_reflecting_.py
    op.drop_table('admin_invite_codes')
========
>>>>>>>> main:migrations/versions/a4eeffcdd4c4_clean_initial_migration_reflecting_.py
    # ### end Alembic commands ###
