"""Add duration_seconds to TapSession

Revision ID: 1ac2b13994ad
Revises: eee779989ddd
Create Date: 2025-06-14 01:53:36.159993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac2b13994ad'
down_revision = 'eee779989ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
