"""Add is_paid column to tap_sessions

Revision ID: 2f2dccbccc06
Revises: 1ac2b13994ad
Create Date: 2025-06-15 03:45:13.635256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2dccbccc06'
down_revision = '1ac2b13994ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
