"""Initial clean migration

Revision ID: 3a0267b9f56d
Revises: 
Create Date: 2025-04-13 03:40:19.929714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a0267b9f56d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('qr_id', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=256), nullable=False),
    sa.Column('block', sa.String(length=1), nullable=False),
    sa.Column('passes_left', sa.Integer(), nullable=True),
    sa.Column('last_tap_in', sa.DateTime(), nullable=True),
    sa.Column('last_tap_out', sa.DateTime(), nullable=True),
    sa.Column('is_rent_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_property_tax_enabled', sa.Boolean(), nullable=True),
    sa.Column('owns_seat', sa.Boolean(), nullable=True),
    sa.Column('insurance_plan', sa.String(), nullable=True),
    sa.Column('insurance_last_paid', sa.DateTime(), nullable=True),
    sa.Column('second_factor_type', sa.String(), nullable=True),
    sa.Column('second_factor_secret', sa.String(), nullable=True),
    sa.Column('second_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('has_completed_setup', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_id')
    )
    op.create_table('tap_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('tap_in_time', sa.DateTime(), nullable=True),
    sa.Column('tap_out_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # op.drop_table('student')  # Commented out to prevent conflict with foreign keys

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_student_id_fkey', 'student', ['student_id'], ['id'])

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_student_id_fkey', 'student', ['student_id'], ['id'])

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('qr_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pin_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('block', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('passes_left', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_tap_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_tap_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_rent_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_property_tax_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owns_seat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('insurance_plan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('insurance_last_paid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('second_factor_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('second_factor_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('second_factor_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_completed_setup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_pkey'),
    sa.UniqueConstraint('qr_id', name='student_qr_id_key')
    )
    op.drop_table('tap_sessions')
    op.drop_table('students')
    # ### end Alembic commands ###
