"""Add dob_sum to Student model

Revision ID: eb0c1d9a3756
Revises: 9297b7e933f1
Create Date: 2025-06-30 19:52:29.308103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0c1d9a3756'
down_revision = '9297b7e933f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob_sum', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dob_sum')

    # ### end Alembic commands ###
